// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ui

type UserConsentVerifierAvailability int32

const SignatureUserConsentVerifierAvailability string = "enum(Windows.Security.Credentials.UI.UserConsentVerifierAvailability;i4)"

const (
	UserConsentVerifierAvailabilityAvailable            UserConsentVerifierAvailability = 0
	UserConsentVerifierAvailabilityDeviceNotPresent     UserConsentVerifierAvailability = 1
	UserConsentVerifierAvailabilityNotConfiguredForUser UserConsentVerifierAvailability = 2
	UserConsentVerifierAvailabilityDisabledByPolicy     UserConsentVerifierAvailability = 3
	UserConsentVerifierAvailabilityDeviceBusy           UserConsentVerifierAvailability = 4
)
