// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ui

type UserConsentVerificationResult int32

const SignatureUserConsentVerificationResult string = "enum(Windows.Security.Credentials.UI.UserConsentVerificationResult;i4)"

const (
	UserConsentVerificationResultVerified             UserConsentVerificationResult = 0
	UserConsentVerificationResultDeviceNotPresent     UserConsentVerificationResult = 1
	UserConsentVerificationResultNotConfiguredForUser UserConsentVerificationResult = 2
	UserConsentVerificationResultDisabledByPolicy     UserConsentVerificationResult = 3
	UserConsentVerificationResultDeviceBusy           UserConsentVerificationResult = 4
	UserConsentVerificationResultRetriesExhausted     UserConsentVerificationResult = 5
	UserConsentVerificationResultCanceled             UserConsentVerificationResult = 6
)
